chore: added tf plan in the mix

diff --git a/.github/workflows/n8n-plan.yaml b/.github/workflows/n8n-plan.yaml
--- a/.github/workflows/n8n-plan.yaml
+++ b/.github/workflows/n8n-plan.yaml
@@ -28,3 +28,34 @@ jobs:
         working-directory: ./terraform
         run: | 
           terraform init
+      
+      - name: Terraform Format
+        working-directory: ./terraform
+        run: terraform fmt -check
+
+      - name: Terraform Validate
+        working-directory: ./terraform
+        run: terraform validate
+
+      - name: Terraform Plan
+        working-directory: ./terraform
+        id: tf-plan
+        run: |
+          export exitcode=0
+          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+          if [ $exitcode -eq 0 ]; then
+            echo "Terraform plan succeeded"
+            exit 0
+          else
+            echo "Terraform plan failed"
+            exit 1
+          fi
+
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v4
+        with:
+          name: tfplan
+          path: ./terraform/tfplan
